all:				clock.bin

clock.bin:			clock.c videodisp.c videodisp.h ../io-kraft80/io-kraft80.h ../io-kraft80/crt0-kraft80-loadable.rel ../io-kraft80/io-kraft80.rel 
				sdcc -c -V --disable-warning 85 -mz80 -I../io-kraft80 --opt-code-size --std-sdcc99 clock.c
				sdcc -c -V --disable-warning 85 -mz80 -I../io-kraft80 --opt-code-size --std-sdcc99 videodisp.c
				#sdcc -mz80 --code-loc 0x2A00 -DUSE_KRAFTMON=1 --no-std-crt0 -Wl -b_MAIN=0x2100,-b_DATA=0x3300 ../io-kraft80/crt0-kraft80-loadable.rel ../io-kraft80/io-kraft80.rel clock.rel videodisp.rel
				sdcc -mz80 --code-loc 0x4B00 -DUSE_KRAFTMON=0 --no-std-crt0 -Wl -b_MAIN=0x4200,-b_DATA=0x5400 ../io-kraft80/crt0-kraft80-loadable.rel ../io-kraft80/io-kraft80.rel clock.rel videodisp.rel
				mv crt0-kraft80-loadable.ihx clock.ihx
				objcopy --input-target=ihex --output-target=binary clock.ihx clock.bin

clean:
				rm -f *.ihx *.map *.sym *.lk *.rel *.lst *.noi *.asm *.mem *.hex *.bin

